created create guild button which opens a dialog that allows you to create a created guild with the create guild api in create created create guild
EmirhanTr3/Whitespace pull request #2
Opened 2024-09-18 14:13 UTC by aspectxlol

2024-09-18 14:14 UTC, aspectxlol commented
src/components/dialogs.tsx
src/pages/index.tsx

2024-09-18 14:16 UTC, aspectxalt requested changes

2024-09-18 14:16 UTC, aspectxalt commented on package.json
should remove package manager, since the project doesnt use yarn

2024-09-18 14:16 UTC, aspectxalt commented on src/components/dialogs.tsx
change the default color from white to a darker color to attract more basement adults

2024-09-18 14:16 UTC, aspectxalt commented on start-database.sh
should remove this file, since the project uses Pterodactyl

2024-09-18 14:17 UTC, aspectxalt commented on src/components/dialogs.tsx
project owner did not specify a color theme, default was white

2024-09-18 14:17 UTC, aspectxlol commented on src/components/dialogs.tsx
project owner did not specify a color theme, white was the default color theme

2024-09-18 14:18 UTC, aspectxlol commented on start-database.sh
pull author does not have a pterodactyl setup, therefor pull author relies on docker to setup a working postgresql database

2024-09-19 03:47 UTC, aspectxlol commented
@EmirhanTr3 pls review

2024-10-03 20:46 UTC, EmirhanTr3 commented
Added in [3c1b208](https://github.com/EmirhanTr3/Whitespace/commit/3c1b2080e9df83991029cb1309c9c38ee1f88bc4)

2024-10-03 20:46 UTC, closed without merging